language: generic
sudo: required
services:
        - docker


before_install:
        - docker build -t galsuser/docker-react -f Dockerfile.dev .

script:
        - docker run -e CI=true galsuser/docker-react npm run test
